### ISSUE TITLE
Current block height: 16371 

### ISSUE THREAD

**Issue by senhanxiao** [CityOfZion/neo-local#131]
Current block height: 16371
一直16371，区块连浏览器不更新。节点在生成区块。什么原因

**Comment by nunojusto** [comment]
I've used google translate to english to understand your message. Hope i'm right.

You are saying that the neo-scan only have block 16371 but the nodes are generating new blocks without problem.
Well, it might me a problem with neo-scan container. You can restart neo-scan with these commands on linux:
```
docker-compose stop neo-scan-api
docker-compose restart neo-scan-sync
docker-compose start neo-scan-api
```
That should correct it.

**Comment by revett** [comment]
@senhanxiao Did that help?

**Comment by nunojusto** [comment]
No further comments, i will close this issue
