### ISSUE TITLE
Claiming bug on neo-local-faucet

### ISSUE THREAD

**Issue by nunojusto** [CityOfZion/neo-local#156]
## Summary

As discussed here https://github.com/CityOfZion/neo-local/pull/153
Thanks to @archaengel, for discovering this.
neo-local-faucet service fails to process request from any wallet with default env variable BOOTSTRAP=_4kBlocks. Chain height of < 5000 breaks service and cause infinite loop in container.

## To Reproduce

Try to claim assets using neo-local-faucet.

## Expected Behaviour

Claim success

**Comment by nunojusto** [comment]
@archaengel, please confirm this is corrected, to close this issue.

**Comment by archaengel** [comment]
Can confirm the faucet's working like a charm, @nunojusto.
> <img width="767" alt="screen shot 2019-03-02 at 12 27 14 pm" src="https://user-images.githubusercontent.com/36070056/53687209-bb0f5680-3ce6-11e9-9f85-9dd3312181f9.png">
Thanks so much, my friend! :bowing_man:
