### ISSUE TITLE
Reduce needed resources (RAM+CPU)

### ISSUE THREAD

**Issue by nunojusto** [CityOfZion/neo-local#167]
## Describe the Solution

Having 11 containers running uses a lot of RAM+CPU resources.
We need a lighter way to run a private blockchain. And have a way to choose the full or light version.

## Why?

On some old computers it's very difficult to run neo-local

**Comment by kokahunter** [comment]
Maybe this helps? 
[Allowing privatenet with single CN to generate block](https://github.com/neo-project/neo/pull/705)

**Comment by nunojusto** [comment]
https://github.com/CityOfZion/neo-local/issues/174
solves this issue

**Comment by nunojusto** [comment]
Solved here
https://github.com/CityOfZion/neo-local/pull/187
