### ISSUE TITLE
Notifications-Server - Drive has not been shared

### ISSUE THREAD

**Issue by shaddow1201** [CityOfZion/neo-local#173]
## Summary
Any thoughts ?
Creating neo-cli-privatenet-4 ... done
Creating postgres             ... done
Creating neo-cli-privatenet-2 ... done
Creating neo-cli-privatenet-1 ... done
Creating neo-cli-privatenet-3 ... done
Creating notifications-server ... error

ERROR: for notifications-server  Cannot create container for service notifications-server: b'Drive has not been shared'

ERROR: for notifications-server  Cannot create container for service notifications-server: b'Drive has not been shared'
ERROR: Encountered errors while bringing up the project.

## To Reproduce

following Simple Setup
After: Run docker-compose up.

## Expected Behaviour
Not to have Errors while bringing up the project

## Docker

Which version... 18.09.2

## Docker Compose

Which version... 1.23.2

## Operating System

Are you running Mac, Windows or Linux...  Windows

## Screenshots
https://www.screencast.com/t/4uNEAc6dFdX8

**Comment by nunojusto** [comment]
This is corrected in the develop branch.
Please use that branch or wait a few days to be merged in the master branch.
