### ISSUE TITLE
New Image for neo-cli 2.10.2

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neo-local#174]
## Describe the Solution

Requesting a new docker image for neo-cli v2.10.2

## Why?

v2.10.1 has a VM issue which is mitigated in v2.10.2

**Comment by nunojusto** [comment]
I've created a special experimental branch for this.
It's the name: experimental/solo-node-consensus

This implementation changes a lot of things and ew need to test all before going to master.
If you want to test, please report back any errors or improvements

**Comment by Ashuaidehao** [comment]
I'm using this branch for testing smart contract.How can I open the "wallet1_solo.json" wallet to claim gas?

**Comment by nunojusto** [comment]
You need to wait for a certain amount of blocks to be produced to be able to claim GAS. If you have time, i recommend 6k blocks and use the Faucet at port 4002
But then the opening of wallets works as before. No change.

**Comment by Ashuaidehao** [comment]
Get it!
Solo node mode seems to be very useful for developers , I wanna to know when it would be ready to be merged , thanks!

**Comment by nunojusto** [comment]
Well, solo node mode will be merged tomorrow to develop branch and 2 weeks after to Master. That's my plan

**Comment by Ashuaidehao** [comment]
Hi @nunojusto , the neo-scan-api container will fault each time I reboot my system. I find this is mostly because the postgres container which neo-scan-api depends on is not enable "Always" restart policy. Can you have a look?
![neo-local issue](https://user-images.githubusercontent.com/7391819/61194906-600b5880-a6f7-11e9-8da9-61f7ef7a8a42.png)

**Comment by Ashuaidehao** [comment]
Hi @nunojusto ,I'm trying to make a PR(https://github.com/CityOfZion/neo-local/pull/180) to fix my problem. How is solo node mode going now ?

**Comment by nunojusto** [comment]
I've merged your request. Thanks.

This solo node release is somehow blocked by a bug in the initial NEO+GAS claim.
We're figuring out what to do.
It will take a little more time.

**Comment by Ashuaidehao** [comment]
Hi @nunojusto, is there any update about the new image? Do you have any plan to prepare a neo-cli 2.10.3 image?

**Comment by nunojusto** [comment]
2.10.2 is almost complete and oing for 2.10.3 will be fast. I will need one more week

**Comment by nunojusto** [comment]
It's now complete.
We have a working solo consensus node blockchain that you can test and report errors. I will merge this to develop in a few days if not critical errors are reported. And then merge to master
