### ISSUE TITLE
Claim GAS and NEO script endless loop 

### ISSUE THREAD

**Issue by nunojusto** [CityOfZion/neo-local#179]
## Summary

USING BRANCH:
https://github.com/CityOfZion/neo-local/tree/experimental/solo-node-consensus
from issue https://github.com/CityOfZion/neo-local/issues/174

When trying to claim initial GAS and NEO from genesis wallets using the script
/neo-python/scripts/claim_neo_and_gas_fixedwallet.py

```root@568a98bc081f:/neo-python# python3 scripts/claim_neo_and_gas_fixedwallet.py 
Privatenet useragent '/Neo:2.10.2/', nonce: 185435511
Blockchain DB path: /root/.neopython/Chains/privnet
Warning: Chain database already exists. If this is from a previous private network, you need to delete /root/.neopython/Chains/privnet
[I 190716 22:11:26 LevelDBBlockchain:112] Created Blockchain DB at /root/.neopython/Chains/privnet 
Waiting for chain to sync...
Waiting for chain to sync...
Waiting for chain to sync...
Waiting for chain to sync...
Waiting for chain to sync...
Waiting for chain to sync...
```
And stays looping waiting for sync

## To Reproduce

`docker exec -it neo-cli-privatenet-1 bash` to use shell inside neo-cli container

and then go to /neo-python and

`python3 scripts/claim_neo_and_gas_fixedwallet2.py`

## Expected Behaviour

GAS and NEO being claimed to a private wallet

## Docker

N/A

## Docker Compose

N/A

## Operating System

Linux...

**Comment by Ashuaidehao** [comment]
![WeChat Image_20190730145024](https://user-images.githubusercontent.com/7391819/62107196-a78a0b00-b2d9-11e9-8bbb-8a8d20be9db8.png)
When I enter in the neo-cli-privatenet-1 container , I could not find the "neo-python/scripts/" directory anymore. How can I it reproduce it ? The image is "cityofzion/neo-local-privatenet:2.10.2_genesis".

**Comment by nunojusto** [comment]
Ho, yes, I forgot and did the default cleanup before building the image. I will build another later today and inform.

**Comment by Ashuaidehao** [comment]
Hi @nunojusto , is there any update? Maybe I can help.

**Comment by nunojusto** [comment]
@Ashuaidehao , please remove your local image cityofzion/neo-local-privatenet:2.10.2_genesis and run again `make start` to get the new image with the script inside /neo/python folder.
Then you can test it and try to help.
Thank you

**Comment by Ashuaidehao** [comment]
![WeChat Image_20190809105751](https://user-images.githubusercontent.com/7391819/62751004-b4a2b900-ba94-11e9-8fa9-00febde99c96.png)

The "python3" works in the new image,but I still can't find the "claim_neo_and_gas_fixedwallet2.py".
Is this script necessary? I prefer to claim all the neo and gas with some other tool like neo-gui .

**Comment by nunojusto** [comment]
Sorry, forget the number 2.
It's claim_neo_and_gas_fixedwallet.py

**Comment by Ashuaidehao** [comment]
Yes, I set neo-gui's "config.json" and "protocal.json" in accord with the solo node config files. Then use neo-gui opening the "wallet_solo.json" file, it works perfectly.
![solo1](https://user-images.githubusercontent.com/7391819/62766282-ab314500-bac4-11e9-829e-460fcc1839f1.png)

![solo2](https://user-images.githubusercontent.com/7391819/62766293-b08e8f80-bac4-11e9-9430-3e74e3b911d4.png)

**Comment by nunojusto** [comment]
Well, that great to know, but we need a 'terminal command way' to do auto-magically.
But, we can know see the problem is related to the way the python script does the claim.

**Comment by Ashuaidehao** [comment]
Hi @nunojusto, I have tested it and found it is mostly because the scripts use the the wrong config file to setup neo-python node.
Here are my some modify to fix it(https://github.com/Ashuaidehao/neo-local/commit/57a4fea05753c3a0f49567837f751db84574f251).
You can follow my steps to claim all  the neo:

1. copy my 2 files into the container:
```sh
docker cp claim_neo_solonet.py neo-cli-privatenet-1:/neo-python/
docker cp protocol.solo.json neo-cli-privatenet-1:/neo-python/
```
2. enter the container and run my new scripts:
![solo_fix1](https://user-images.githubusercontent.com/7391819/63140929-37d48980-c016-11e9-88f6-bca1cfc407c5.png)

The result:
![solo_fix2](https://user-images.githubusercontent.com/7391819/63140958-66526480-c016-11e9-86eb-4fd096bbc228.png)

The most important step is using the sole net config file to setup the neo-python node(https://github.com/Ashuaidehao/neo-local/blob/57a4fea05753c3a0f49567837f751db84574f251/privnet/scripts/claim_neo_solonet.py#L261) and cleaning old private chain data before run the scripts.

Hope it is helpful to build a new image.

**Comment by nunojusto** [comment]
Thank you for your investigation, but I've found the same yesterday (you can see it in our Slack).
There are 2 ways we can do this, or we change the cloned neo-ptython repo and put there the good config, or we change our script to override the config path, like you have in your approach.
I like the second approach.
Do you want to make a PR yourself? If so, please commit to privnet/scripts/claim_neo_and_gas_fixedwallet2.py
And then later I will rename the file and build the image

**Comment by nunojusto** [comment]
Thanks @Ashuaidehao
