### ISSUE TITLE
[] being treated like a string and not an array

### ISSUE THREAD

**Issue by WyattMufson** [CityOfZion/neo-local#182]
## Summary

I am testing a basic NEP-11 contract. I am running the `name` method with an empty array of arguments.

If I run 
```
sc build_run /smart-contracts/contract.py True False False 0710 05 name []
```
it treats the arguments as being the string `"[]"` and has a length of 2. If I do
```
sc build_run /smart-contracts/contract.py True False False 0710 05 name ["a"]    
```
it treats the arguments as an array with one item `"a"` in it.

## To Reproduce

Cloned neo-local
Ran `make start`
Opened a wallet
Ran the command

## Expected Behaviour

`[]` should be treated as an empty array, not `"[]"`.

## Docker

Docker Desktop Community 2.0.0.3 (31259)

## Docker Compose

Not sure, I think 3.4?

## Operating System

macOS 10.14.4

**Comment by nunojusto** [comment]
Can you run this test in a develop branch. I thinks that's a bug already corrected.

**Comment by nunojusto** [comment]
Closing because of no reply
