### ISSUE TITLE
About neo-cli-privatenet-x

### ISSUE THREAD

**Issue by WAELKASSEM** [CityOfZion/neo-local#191]
## Summary
only neo-cli-privatenet-1 is starting.
## To Reproduce
1.  make start

## Expected Behaviour

I expect that neo-cli-privatenet-1 , neo-cli-privatenet-2 , neo-cli-privatenet-3 , neo-cli-privatenet-4 
also start , LIKE the course provided on NEO academy.

## Docker
 Client: Docker Engine - Community
 Version:           19.03.8
## Docker Compose
docker-compose version 1.25.4, build 8d51620a

## Operating System
Ubuntu 18.04.4 LTS

## Screenshots
![image](https://user-images.githubusercontent.com/37499489/77072164-ef3edd80-69f5-11ea-8225-dc9e9dbdab11.png)

**Comment by nunojusto** [comment]
Hello.
NEO-local is now a single node system.
Some changes made possible to have only one node for local development purposes.
This way we do not clog resources and all works the same. To develop application we don't really need consensus if we only have our transactions and deploys.
That's the reason you don't see other nodes being started and that's normal.

Thank you for posting this issue.
I will close it if you agree.

I will try to contact Neo Academy to help them update their documentation.

**Comment by WAELKASSEM** [comment]
Agree !!!!! Thank you very much for your instant reply .
