### ISSUE TITLE
Document usage on Windows

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-local#2]
How can I use this on Windows? Add some documentation. There is no reason that shouldn't be possible -- Docker works just fine, and a lot of devs actually use Windows.

So I think documentation on how to get the setup up and running on Windows is quite critical to reach the full potential of this setup.

via @revett: Is there a make equivalent for Windows?

**Comment by revett** [comment]
Closing as solved by documentation that is now in README: https://github.com/CityOfZion/neo-local#windows-1
