### ISSUE TITLE
Cannot start service neo-nodes

### ISSUE THREAD

**Issue by DalderupMaurice** [CityOfZion/neo-local#39]
Got this error for a while now, not sure what's the root of the problem. 
Removed all images/containers, restarted docker, pulled latest branch, but that doesn't seem to resolve anything.

```
ERROR: for neo-nodes  Cannot start service neo-nodes: driver failed programming external connectivity on endpoint neo-noCreating postgres  ... done
.0.0.0:30336:tcp:172.18.0.3:30336: input/output error

ERROR: for neo-nodes  Cannot start service neo-nodes: driver failed programming external connectivity on endpoint neo-nodes (f427c0b37614765e32aa5d69ee8fa9c015369598068cd7524355baa8020f1881): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:30336:tcp:172.18.0.3:30336: input/output error
ERROR: Encountered errors while bringing up the project.
```

![](https://i.imgur.com/CezKRFS.png)

**Comment by DalderupMaurice** [comment]
On my mac, it's forever stuck on this:
 
![image](https://user-images.githubusercontent.com/10922045/44308346-22516300-a3b4-11e8-8c57-31321035242b.png)

The original issue is on my windows PC

**Comment by jeroenptrs** [comment]
@DalderupMaurice what version is neo-privatenet pulling? Can you look for the version and date for `cityofzion/neo-privatenet` using `docker images ls`?

Additionally, could you try removing that image with `docker rmi IMAGE_ID` and do a `make start` again?

@metachris I verified with Maurice privately, this issue happens for him using solely the neo-privatenet docker so it feels partially unrelated to neo-local, could you check and verify with him too please?

**Comment by DalderupMaurice** [comment]
```
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
cityofzion/neo-privatenet   latest              aa9992e81b4f        7 weeks ago         2.79GB
```
Removed all containers/images and tried only with neo-privnet as @jeroenptrs said - still doesn't work. This is the result of `docker images ls`

**Comment by DalderupMaurice** [comment]
Issue on mac is resolved, it just gets stuck on `docker-compose pull` no clue why

**Comment by DalderupMaurice** [comment]
Hmm, solved it somehow 🤔 Last thing I did was a registry clean with CCleaner, worked after that 😅
