### ISSUE TITLE
[neo-local] Waiting for network......... takes a looong time

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-local#4]
When running `make start`, the step which shows `[neo-local] Waiting for network...................` takes too long, like 2 minutes or even more. Why is that? Doesn't seem necessary. The original privnet container starts immediately, so does neo-python.

**Comment by revett** [comment]
Closing this issue as it is related to the startup time of [neo-scan](https://github.com/CityOfZion/neo-scan) locally and not this project.
