### ISSUE TITLE
Break out privatenet in separate dockers

### ISSUE THREAD

**Issue by jeroenptrs** [CityOfZion/neo-local#47]
Effect AI already does this https://github.com/effectai/neo-dev-toolkit/blob/master/docker-compose.yml and we can always keep the neo-privatenet docker image for developers that need a *quick* setup, but this caters to more use cases:

* Occasionally a node goes offline, we should be able to simply start and restart nodes (potentially even from the CLI!). 
* In a way, learning to work with consensus nodes (adding a new one to the already existing pool f.e.) can also be a learning experience for developers interested in DBFT.

These two key points are more easily possible if we break out the consensus nodes in separate dockers.

**Comment by nunojusto** [comment]
-= Assigned to nunojusto =-

**Comment by nunojusto** [comment]
Hours of work on this.
Please use this MVP to test it.
Clone my own git for that:
https://github.com/nunojusto/neo-local/tree/4-isolated-consensus-nodes

**Comment by nunojusto** [comment]
@revett and @jeroenptrs 
Consensus nodes started like this, but for some reason there's no blocks yet:

```spawn dotnet neo-cli.dll --rpc
NEO-CLI Version: 2.7.4.0

neo> open wallet wallet1.json
open wallet wallet1.json
password: ***
neo> start consensus
[21:13:42] OnStart
[21:13:42] initialize: height=1 view=0 index=2 role=Backup
[21:14:12] timeout: height=1 view=0 state=Backup
[21:14:12] request change view: height=1 view=0 nv=1 state=Backup, ViewChanging
[21:15:12] timeout: height=1 view=0 state=Backup, ViewChanging
[21:15:12] request change view: height=1 view=0 nv=2 state=Backup, ViewChanging
```

what could be happening?

**Comment by nunojusto** [comment]
Found the bug, it was a bad path...
![image](https://user-images.githubusercontent.com/21068187/46507688-ac08a300-c831-11e8-9fd1-ce29b7b3a462.png)

**Comment by nunojusto** [comment]
I've created a new branch for neo-local called 4-isolated-consensus-nodes
That way we can test this and if it's OK, we can merge back to master

**Comment by nunojusto** [comment]
Another step achieved: _One image to rule them all_
Consensus nodes are now a single smaller (777MB) standard image spawned in 4 containers.
Notable advantages:
- 4x faster to build
- 1/4 storage space

![image](https://user-images.githubusercontent.com/21068187/46635695-2ea0a380-cb4d-11e8-9d31-c3924362370c.png)

**Comment by nunojusto** [comment]
**More steps completed:**
- Multi neo-cli version can be setup from the .env file.
Note: And we can even mix various versions inside the same privatenet, like if it was a testnet/mainnet

Next step is publish the docker image to docker hub.
I'm waiting for a chain to become long enough.

**Comment by nunojusto** [comment]
Conainers commited and pushed to the newly official docker repo cityofzion/neo-local-privatenet

**Comment by nunojusto** [comment]
https://github.com/CityOfZion/neo-local/pull/92
