### ISSUE TITLE
NeoScan timeout in nightly builds

### ISSUE THREAD

**Issue by revett** [CityOfZion/neo-local#52]
## Problem

**TLDR**: The nightly builds are failing due to a timeout.

See build [#296](https://travis-ci.org/CityOfZion/neo-local/builds/431498506) as an example.

The nightly builds starts the Compose stack and then runs a test to check that all of the containers have been started and are still running. During the Compose stack starting, it will wait for NeoScan to start. This is what is timing out in the build.

**Comment by jeroenptrs** [comment]
@revett with the neoscan update, is this fixed?

**Comment by revett** [comment]
I haven't been seeing this anymore so I'm going to close this issue.

Looks good since we moved to the split neoscan containers 👍
