### ISSUE TITLE
Test for latest Docker images

### ISSUE THREAD

**Issue by revett** [CityOfZion/neo-local#54]
## Idea

This project pins the version of the Docker images it uses because of breaking changes that occur in upstream projects that it consumes.

This however means that it regularly falls out of date as these projects regularly post updates.

It would be good to have automated tests to check that the Docker image versions are the latest. 

These test should be run within the nightly test suite.

**Comment by nunojusto** [comment]
We can do this with webhook and docker hub.
All images posted to docker hub can alert our Slack channel.... in a breeze :)
I need to think in a way to do the same for neo-scan that does not use docker hub to publish their images.
