### ISSUE TITLE
neo-scan stops syncing on minttokens (c#)

### ISSUE THREAD

**Issue by jeroenptrs** [CityOfZion/neo-local#58]
Not related to stack isolation flags since @deanpress fixed this, so a token contract succesfully deploys on neo-local, neoscan just halts syncing the second you mint tokens in a token sale context

**Comment by revett** [comment]
@jeroenptrs Does this only happen when using NeoScan within neo-local? Or does it also occur when running NeoScan on its own locally?

**Comment by jeroenptrs** [comment]
I'd need a postgres and notification-server instance to run neo-scan, so I'm wondering if there's any difference in separate or within the neo-local network? Unless you're talking about coupling it to a non local network?
