### ISSUE TITLE
NeoScan doesn't detect transaction output in invocation transactions

### ISSUE THREAD

**Issue by xxedocxx** [CityOfZion/neo-local#66]
**Describe the bug**
I found the bug when I worked on Cgas and Cneo contracts. Neoscan does not read outputs and asset transfers in invocation transactions.
For example:
I send a Cgas mint invocation with 10 NEO. In the chain it works but Neoscan does not show the transfer and correct balance.

**Comment by revett** [comment]
Hi @xxedocxx, thanks for raising this issue 👍 

Is this issue specific to when NeoScan is run within neo-local? If it is general issue with NeoScan then it is better to raise the issue in that repo:

https://github.com/CityOfZion/neo-scan

**Comment by revett** [comment]
cc/ @adrienmo - Is this a known issue?

**Comment by adrienmo** [comment]
@revett I am not sure it is related but, I got some report about NEP-8 enabled contracts would not work properly with the notification server. Basically for all NEP-5 transfer, it is the duty of the notification to parse it and make it available for neoscan. If there is a transfer not shown on neoscan it probably comes from the notification server.

**Comment by xxedocxx** [comment]
I appreciate your contribution. 

I think this issue is related to @adrienmo mentioned because it works fine with Testnet neo-scan and my previous neo-scan docker (https://github.com/slipo/neo-scan-docker).

**Comment by revett** [comment]
Okay thanks @xxedocxx @adrienmo, I'm going to close this issue as it is a problem with the services within the neo-local stack and not neo-local itself.
