### ISSUE TITLE
Should we change to git flow?

### ISSUE THREAD

**Issue by revett** [CityOfZion/neo-local#76]
## Problem

Currently we make a new release for **every** merge to master, which is kind of ridiculous...

It adds adds unnecessary admin overhead to the project and users don't have a clear idea of when a new release contains a README change compared to a new Docker service.

## Solution

Should we follow git flow?

See: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by jeroenptrs** [comment]
The process I maintain on most projects is squash merge feature branches to develop, and regular commit merge from develop to master, with versioning happening either right before merging to master (so they're merged with, comes in handy if you want the changelog to be on develop as well) or after (if you don't care about a changelog on develop)

**Comment by revett** [comment]
This has now been implemented!
