### ISSUE TITLE
Windows portability

### ISSUE THREAD

**Issue by canesin** [CityOfZion/neo-local#8]
Unfortunately Makefiles are not easily supported in the platform 90% of the developers of the world use.

**Comment by metachris** [comment]
Perhaps we should just show the 2 commands that are needed directly:

    docker-compose up
    docker exec -it neo-python np-prompt -p -v

Not sure we even need the wrapper/Makefile...

**Comment by revett** [comment]
@canesin I am working on porting the contents of the `Makefile` to a cross-platform CLI. This will also allow us to unit test the project.

**Comment by revett** [comment]
Closing as solved by documentation that is now in README: https://github.com/CityOfZion/neo-local#windows-1

This will be improved in the future by the CLI, however I've seen Windows users run the project so I'm happy for the moment.
