### ISSUE TITLE
Container Name Already In Use

### ISSUE THREAD

**Issue by revett** [CityOfZion/neo-local#85]
<img width="902" alt="image" src="https://user-images.githubusercontent.com/2796074/47321290-41869e00-d64c-11e8-9fe2-018bc2d7e7ae.png">

## Problem

The CLI heavily uses container names to check the state of the containers that have been started.

It does not take into consideration when creating new containers that one with the same name may already exist.

**Comment by nunojusto** [comment]
we need a stop command (or down command)
