### ISSUE TITLE
neo-local doesn't work offline

### ISSUE THREAD

**Issue by belane** [CityOfZion/neo-local#89]
**Is your feature request related to a problem? Please describe.**
Make it work offline when you already have the necessary images.
When using `make start` offline, it fails trying to download the images even when they are already available locally.

**Describe the solution you'd like**
Perhaps `make start-offline`

**Describe alternatives you've considered**
It fails in https://github.com/CityOfZion/neo-local/blob/master/Makefile#L26, if you comment this line works as workarround.

**Comment by belane** [comment]
I've tested https://github.com/CityOfZion/neo-local/pull/94 and the new command `make start-offline` works perfectly offline.
I think we can close this issue.

**Comment by revett** [comment]
Thanks @belane 🎉
